var fs = require("fs")
var file = fs.readFileSync("example.pwf").toString()
var result = "<!--Auto-generated by pwf parser.-->\n"+file
var regs = {
	"/\/\/(.+)/g":"<!--$1-->"
}
function tag(name,content="",flags={}){ // Make an XML tag.
	var data = `<${name}`
	if(Object.keys(flags).length){
		var f = ""
		Object.keys(flags).forEach((flag)=>{
			f += " "
			f += flag
			f += "=\""
			f += flags[flag]
			f += "\""
		})
		data += ` ${f}`
	}
	if(!content){
		data += " />"
	}else{
		data += ">"
		data += content
		data += `</${name}>`
	}
	return data
}
var pass1 = Array.from(result.match(/\s(.)>[\S\s]*\s+<\1/g))
console.log(pass1)
Object.keys(regs).forEach((reg)=>{
	var cmps = reg.match(/\/(.*)\/(.*)/)
	var r = new RegExp(cmps[1],cmps[2])
	result = result.replace(r,regs[reg])
})
result = pass1.join("\nBLOCK\n")
fs.writeFileSync("result.xml",result)